server:
  port: 32012
  tomcat:
    accesslog:
      enabled: true
      pattern: '%h %l %u %t "%r" %s %b %D'
      directory: accesslogs
      buffered: false
    basedir: ./logs

APPLICATION_ID: mylearning-servicecomb
service_description:
  name: servicecomb2servlet
  version: 0.0.1
  environment: development
cse:
  service:
    registry:
      address: https://cse.cn-north-1.myhuaweicloud.com
#      address: http://192.168.0.125:30100
      instance:
        watch: false
  config:
    ignoreResolveFailure: true
    client:
      serverUri: https://cse.cn-north-1.myhuaweicloud.com
      refreshMode: 1
      refresh_interval: 5000
  monitor:
    client:
      serverUri: https://cse.cn-north-1.myhuaweicloud.com
      enabled: false
  metrics:
    publisher:
      defaultLog:
        enabled: false
  rest:
    address: 0.0.0.0:32012
    servlet:
      urlPattern: /rest/*
  credentials:
    accessKey: ${AK}
    secretKey: ${SK}
  #    project: cn-north-1
  #    akskCustomCipher: default
  accesslog:
    enabled: true
    pattern: "%h - - %t cs-uri %s %B %D %SCB-traceId"
  uploads:
    directory: uploadTemp

servicecomb:
  codec:
    printErrorMessage: true

#ssl:
#  #  ciphers: TLS_RSA_WITH_AES_256_GCM_SHA384
#  rest:
#    provider:
#      protocols: TLSv1.2
#      authPeer: false
#      checkCN:
#        host: false
#      trustStore: trust.jks
#      trustStoreType: JKS
#      trustStoreValue: Changeme_123
#      keyStore: server.p12
#      keyStoreType: PKCS12
#      keyStoreValue: Changeme_123
#      crl: revoke.crl
#      sslCustomClass: mylearning.servicecomb.springboot2.servlet.jar.utils.DemoSSLCustom
