#spring:
#  main:
#    web-application-type: none

APPLICATION_ID: mylearning-servicecomb
service_description:
  name: servicecomb1edge
  version: 0.0.0.1
cse:
  service:
    registry:
      address: https://cse.cn-south-1.myhuaweicloud.com:443
      instance:
        watch: false
  config:
    client:
      serverUri: https://cse.cn-south-1.myhuaweicloud.com:443
      refreshMode: 1
      refresh_interval: 5000
  monitor:
    client:
      serverUri: https://cse.cn-south-1.myhuaweicloud.com:443
      enabled: false
  rest:
    address: 0.0.0.0:8000
  credentials:
    accessKey: ${AK}
    secretKey: ${SK}
    project: cn-south-1
    akskCustomCipher: default
  http:
    dispatcher:
      edge:
        url:                               # 使用URLMappedEdgeDispatcher开发网关服务
          enabled: true                    # 开启URLMappedEdgeDispatcher
          mappings:
            # providerV0:                    # 定义名为providerV0的映射规则
            # prefixSegmentCount: 1        # 前缀长度为1，例如接到url为/hello/provider/V0/hello/Bob的请求，截去第一段发给provider
            # path: "/hello/.*"            # 映射规则匹配请求url的正则表达式
            # microserviceName: provider   # 映射规则对应转发的后端微服务
            # versionRule: 0.0.0-1.0.0     # 匹配的微服务版本范围，大于或等于0.0.0，小于1.0.0
            consumerV0:
              prefixSegmentCount: 1
              path: "/client/.*"
              microserviceName: consumer
              versionRule: 0.0.0-1.0.0
        default:
          enabled: true
          prefix: rest
          # withVersion默认值就是true，这里只是展示一下
          withVersion: false #请求带版本号，例如v1表示[1.0.0-2.0.0)范围内的微服务版本
          # prefixSegmentCount默认值就是1，这里只是展示一下
          prefixSegmentCount: 1 #前缀长度为1，例如接到url为/rest/provider/V0/hello/Bob的请求，截去第一段，将/provider/V0/hello/Bob发给provider
  accesslog:
    enabled: true
    pattern: "%h - - %t cs-uri %s %B %D %SCB-traceId"
  uploads:
    directory: uploadtest
servicecomb.config.ignoreResolveFailure: true