server:
  port: 32011

APPLICATION_ID: mylearning-servicecomb
service_description:
  name: springbootservletjar
  version: 0.0.0.1
cse:
  service:
    registry:
      address: https://cse.cn-south-1.myhuaweicloud.com:443
      instance:
        watch: false
  config:
    ignoreResolveFailure: true
    client:
      serverUri: https://cse.cn-south-1.myhuaweicloud.com:443
      refreshMode: 1
      refresh_interval: 5000
#  monitor:
#    client:
#      serverUri: https://cse.cn-south-1.myhuaweicloud.com:443
#      enabled: false
  rest:
    address: 0.0.0.0:32011
  credentials:
    accessKey: ak
    secretKey: sk
#    project: cn-south-1
#    akskCustomerCipher: default
  handler:
    chain:
      Provider:
        default: qps-flowcontrol-provider,bizkeeper-provider
#  cors:
#    enabled: true
#    origin: "*"
#    allowCredentials: false
#    allowedMethod: PUT,DELETE
#    maxAge: 3600