spring:
  main:
    web-application-type: none
#server:
#  port: 8080

APPLICATION_ID: mylearning-servicecomb
service_description:
  name: springboot2vertxjar
  version: 0.0.1
  environment: development
cse:
  service:
    registry:
      address: https://cse.cn-north-1.myhuaweicloud.com:443
      instance:
        watch: false
  config:
    client:
      serverUri: https://cse.cn-north-1.myhuaweicloud.com:443
      refreshMode: 1
      refresh_interval: 5000
  monitor:
    client:
      serverUri: https://cse.cn-north-1.myhuaweicloud.com:443
#      enabled: false
  rest:
    address: 0.0.0.0:8080
  credentials:
    accessKey: ak
    secretKey: sk
    project: cn-north-1
    akskCustomerCipher: default
  accesslog:
    enabled: true
    pattern: "%h - - %t cs-uri %s %B %D %SCB-traceId"
servicecomb.config.ignoreResolveFailure: true
