APPLICATION_ID: mylearning-servicecomb
service_description:
  name: servicecomb2servletwar
  version: 0.0.0.1
cse:
  service:
    registry:
      address: https://cse.cn-north-4.myhuaweicloud.com:443
      instance:
        watch: false
  config:
    client:
      serverUri: https://cse.cn-north-4.myhuaweicloud.com:443
      refreshMode: 1
      refresh_interval: 5000
    ignoreResolveFailure: true
  monitor:
    client:
      serverUri: https://cse.cn-north-4.myhuaweicloud.com:443
      enabled: false
  rest:
    address: 192.168.0.125:8080
#  highway:
#    address: 192.168.0.182:9090
  handler:
    chain:
      Provider:
        default: demo-handler,qps-flowcontrol-provider,bizkeeper-provider
  credentials:
    accessKey: ${AK}
    secretKey: ${SK}
  #    project: cn-south-1
  #    akskCustomCipher: default
server:
  port: 8080