---
swagger: "2.0"
info:
  version: "1.0.0"
  title: "swagger definition for mylearning.servicecomb.constract.service.RPCServiceImpl2"
  x-java-interface: "mylearning.servicecomb.constract.service.RPCService"
basePath: "/contract-provider/v2"
schemes:
  - "http"
consumes:
  - "application/json"
produces:
  - "application/json"
paths:
  /findPerson:
    get:
      operationId: "findPerson"
      parameters:
        - name: "name"
          in: "query"
          required: true
          type: "string"
      responses:
        200:
          description: "response of 200"
          schema:
            $ref: "#/definitions/Person"
  /queryGender:
    get:
      operationId: "queryGender"
      parameters:
        - name: "name"
          in: "query"
          required: true
          type: "string"
      responses:
        200:
          description: "response of 200"
          schema:
            type: "string"
  /savePerson:
    post:
      operationId: "savePerson"
      parameters:
        - in: "body"
          name: "person"
          required: false
          schema:
            $ref: "#/definitions/Person"
      responses:
        200:
          description: "response of 200"
          schema:
            $ref: "#/definitions/Person"
  /savePerson2:
    post:
      operationId: "savePerson2"
      parameters:
        - in: "query"
          name: "name"
          required: true
          type: "string"
        - in: "body"
          name: "person"
          required: false
          schema:
            $ref: "#/definitions/Person"
      responses:
        200:
          description: "response of 200"
          schema:
            $ref: "#/definitions/Person"
  /saveMyDTO:
    post:
      operationId: "saveMyDTO"
      parameters:
        - in: "body"
          name: "myDTO"
          required: true
          schema:
            $ref: "#/definitions/MyDTO"
      responses:
        200:
          description: "response of 200"
          schema:
            $ref: "#/definitions/MyDTO"
definitions:
  Person:
    type: "object"
    properties:
      name:
        type: "string"
      gender:
        type: "string"
    #      data:
    #        description: "data"
    x-java-class: "mylearning.servicecomb.contract.common.Person"
  MyDTO:
    type: "object"
    required:
      - "booleanA"
      - "intA"
      - "stringA"
      - "myObjs"
    properties:
      stringA:
        type: "string"
        pattern: "^[^\\u4e00-\\u9fa5]+$"
      stringB:
        type: "string"
      stringC:
        type: "string"
      intA:
        type: "integer"
        format: "int32"
      intB:
        type: "integer"
        format: "int32"
      intC:
        type: "integer"
        format: "int32"
      booleanA:
        type: "boolean"
      booleanB:
        type: "boolean"
      booleanC:
        type: "boolean"
      myObjs:
        type: "array"
        items:
          $ref: "#/definitions/MyObj"
    x-java-class: "mylearning.servicecomb.contract.common.MyDTO"
  MyObj:
    type: "object"
    required:
      - "objA"
    properties:
      objA:
        type: "string"
        pattern: "^[^\\u4e00-\\u9fa5]+$"
    x-java-class: "mylearning.servicecomb.contract.common.MyObj"