server:
  port: 32012

APPLICATION_ID: mylearning-servicecomb
service_description:
  name: servicecomb1servlet
  version: 0.0.2
#  environment: development
cse:
  service:
    registry:
#      address: https://cse.cn-north-1.myhuaweicloud.com
      address: https://49.4.67.238:30100
      instance:
        watch: false
  config:
    ignoreResolveFailure: true
    client:
#      serverUri: https://cse.cn-north-1.myhuaweicloud.com
      serverUri: https://49.4.67.238:30103
      refreshMode: 1
      refresh_interval: 5000
  monitor:
    client:
      serverUri: https://cse.cn-north-1.myhuaweicloud.com:443
      enabled: false
  metrics:
    publisher:
      defaultLog:
        enabled: false
  rest:
    address: 0.0.0.0:32012
    servlet:
      urlPattern: /cse/*
  credentials:
    accessKey: ${AK}
    secretKey: ${SK}
#    project: cn-north-1
#    akskCustomCipher: default
  accesslog:
    enabled: true
    pattern: "%h - - %t cs-uri %s %B %D %SCB-traceId"
  uploads:
    directory: uploadTemp

servicecomb:
  codec:
    printErrorMessage: true
